version: '3.4'

services:   
   sourcingdb:
    image: mongo

   workerdb:
    image: mongo

   rabbitmq:
    image: rabbitmq:3-management 
    
   phonebook.api:
    image: ${DOCKER_REGISTRY-}phonebookapi
    build:
      context: .
      dockerfile: PhoneBook.Assement.API/Dockerfile

   worker:
    image : ${DOCKER_REGISTRY-}rabbitmqlistenerworker
    build:
     context: .
     dockerfile: WorkerReportService/PhoneBookWorkerService/Dockerfile

   locationreport.api:
    image: ${DOCKER_REGISTRY-}locationreportapi
    build:
      context: .
      dockerfile: LocationReport.API/Dockerfile

